### ISSUE TITLE
Cannot instantiate Module

### ISSUE THREAD

**Issue by jpardobl** [maros/Zway-InfluxDbStats#2]
Hello.

When I download development version 1.04 I get the following error when instantiating the module.

[2016-01-06 13:01:14.185] [I] [core] Notification: error (core): Cannot instantiate module: InfluxDbStats: TypeError: undefined is not a function
[2016-01-06 13:01:14.275] [I] [core] TypeError: undefined is not a function
at AutomationController.instantiateModule (automation/classes/AutomationController.js:287:24)
at AutomationController.createInstance (automation/classes/AutomationController.js:504:14)
at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:656:40)
at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:41)
at automation/WebserverRequestRouter.js:32:35
at WebServer.document_root (automation/Webserver.js:27:11)

To reproduce de error I just:

Download the last development branch: git clone https://github.com/maros/Zway-InfluxDbStats.git InfluxDbStats
Reload the server
Create an app through the web ui
Read the logs and find the upper stack trace.
Thanks!

**Comment by maros** [comment]
Hi,
since the stack trace originates from AutomationController I assume that you have an incomplete installation:
- Did you install BaseModule first?
- Did you instantiate BaseModule?
- Which zway version are you running (2.2.0 is known to have some issues)

**Comment by jpardobl** [comment]
Did you install BaseModule first?

I did not have it installed but now it is installed. The issues persists. I found at google that this error comes up when the name of the folder at modules/ is different from the class, but it is not my case.

Did you instantiate BaseModule?

I can't find the BaseModule al Local Apps.

Which zway version are you running (2.2.0 is known to have some issues)

I am running version 2.2.0, which should I be running instead?

**Comment by maros** [comment]
Could also be a permission issue. Whenever automation engine is not able to read module.json this error occurs.

Please make sure that BaseModule (https://github.com/maros/Zway-BaseModule) is properly set up and instantiated (via App > Local Apps) before setting up any other module depending on it.

I got a couple of bug reports for BaseModule at version 2.2.0 which I cannot investivate myself (don't have access to a 2.2.0 installation). 2.1.1 should work fine.

**Comment by jpardobl** [comment]
With your recomentations everything goes great. Thanks.

BTW your work is awesome.
